### ISSUE TITLE
Please add a license file too

### ISSUE THREAD

**Issue by prepare** [hypeartist/AsmJit#1]
@hypeartist ,

please add a license file too

:)

**Comment by prepare** [comment]
ping @hypeartist 

:)

**Comment by sschoener** [comment]
I'd like to second this request. Without a license, it is impossible to reuse your library :( Please add a license so possible users know how to give credit to you and what usage is legal :)

**Comment by hypeartist** [comment]
@prepare @sschoener Will ZLib suit you? (I am a total nube in all that licensing stuff)

**Comment by sschoener** [comment]
zlib, BSD, and MIT licenses are on the very permissive end of the spectrum; I would generally recommend them :) You cannot really do anything wrong with those -- they basically all say that you are not to blame for any problems caused by your code and your code can be used by whoever in whatever way they please as long as they a) point out if they changed your code and b) give credit to you as the original author. I usually simply slap an MIT license on everything I publish, but zlib is great, too! :)

**Comment by hypeartist** [comment]
@sschoener Thanx for info! Added a MIT license file (didn't find ZLib in templates). Please check if it's ok.

**Comment by prepare** [comment]
Thank you
:)
